apps/account/urls.py
# Imports
from django.urls import path

from apps.account import views as account_views

# Set the app name
app_name = "account"

# URL patterns
urlpatterns = [
    path("login/", account_views.login_view, name="login"),
    path("logout/", account_views.logout_view, name="logout"),
    path("register/", account_views.register_view, name="register"),
    path("profile/", account_views.profile_view, name="profile"),
]

apps/core/urls.py
# Imports
from django.urls import path

from apps.core import views as core_views

# Set the app name
app_name = "core"

# URL patterns
urlpatterns = [
    path("", core_views.home_view, name="home"),
    path("explore/", core_views.explore_view, name="explore"),
]

apps/dashboard/urls.py
# Imports
from django.urls import path

from apps.dashboard import views as dashboard_views

# Set the app name
app_name = "dashboard"

# URL patterns
urlpatterns = [
    path("dashboard/", dashboard_views.home_view, name="home"),
    path(
        "api/playground/getPeriodIntervals/",
        dashboard_views.get_period_intervals_view,
        name="getPeriodIntervals",
    ),
    path(
        "<str:symbol>/playground/", dashboard_views.playground_view, name="playground"
    ),
]

apps/stock/urls.py
# Imports
from django.urls import path

from apps.stock import views as stock_views

# Set the app name
app_name = "stock"

# URL patterns
urlpatterns = [
    path("indices/", stock_views.indices_view, name="indices"),
    path("indices/<str:symbol>/", stock_views.index_quote_view, name="indexQuote"),
    path(
        "indices/<str:symbol>/bookmark/",
        stock_views.index_quote_bookmark_view,
        name="indexQuoteBookmark",
    ),
    path(
        "indices/<str:symbol>/unbookmark/",
        stock_views.index_quote_unbookmark_view,
        name="indexQuoteUnbookmark",
    ),
    path(
        "api/indices/getCategories/",
        stock_views.get_categories_view,
        name="indicesGetCategories",
    ),
    path(
        "equity/topGainers/",
        stock_views.equity_top_gainers_view,
        name="equityTopGainers",
    ),
    path(
        "equity/topLosers/", stock_views.equity_top_losers_view, name="equityTopLosers"
    ),
    path("equity/<str:symbol>/", stock_views.equity_quote_view, name="equityQuote"),
    path(
        "equity/<str:symbol>/bookmark/",
        stock_views.equity_bookmark_view,
        name="equityQuoteBookmark",
    ),
    path(
        "equity/<str:symbol>/unbookmark/",
        stock_views.equity_unbookmark_view,
        name="equityQuoteUnbookmark",
    ),
]

config/urls.py
# Imports
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# Django admin urls
urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
]

# Health check urls
urlpatterns += [path("health/", include("health_check.urls"))]

# App urls
urlpatterns += [
    path("", include("apps.core.urls")),
    path("account/", include("apps.account.urls")),
    path("stock/", include("apps.stock.urls")),
    path("", include("apps.dashboard.urls")),
]

# If the app is in debug mode
if settings.DEBUG:
    # Add Silk profiler urls
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

# Admin configuration
admin.site.site_header = "Stockastic Admin"
admin.site.site_title = "Stockastic Admin"
admin.site.index_title = "Welcome to Stockastic Admin"

apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>
            {% block title %}
                Stockastic
            {% endblock title %}
        </title>
        <!-- Meta Tags for SEO -->
        <meta name="description"
              content="Stockastic - A powerful stock management and monitoring platform built with Django. Features real-time tracking, advanced analytics, and intuitive inventory management. Modern, efficient, and scalable." />
        <meta name="keywords"
              content="stock management, inventory tracking, stock monitoring, django, postgresql, tailwindcss, daisyui, business management, inventory control, stock analytics" />
        <meta name="author" content="Rohit Vilas Ingole (DataRohit)" />
        <meta name="robots" content="index, follow" />
        <!-- Favicon -->
        <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}" />
        <!-- Scripts -->
        <script src="{% static 'js/tailwind.js' %}"></script>
        <script src="{% static 'js/project.js' %}"></script>
        <!-- Stylesheets -->
        <link rel="stylesheet" href="{% static 'css/daisyui.css' %}" />
        <link rel="stylesheet" href="{% static 'css/project.css' %}" />
        {% block head %}
        {% endblock head %}
        <script>let FF_FOUC_FIX;</script>
    </head>
    <body class="h-screen bg-base-100 text-gray-50 flex flex-col"
          data-theme="dark">
        <div class="drawer h-full">
            <input id="my-drawer-3" type="checkbox" class="drawer-toggle" />
            <div class="drawer-content flex flex-col">
                <!-- Navbar -->
                <div class="navbar bg-base-300 flex justify-between">
                    <div class="flex items-center">
                        <div class="flex items-center">
                            <div class="flex-none lg:hidden">
                                <label for="my-drawer-3"
                                       aria-label="open sidebar"
                                       class="btn btn-square btn-ghost">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         fill="none"
                                         viewBox="0 0 24 24"
                                         class="inline-block h-6 w-6 stroke-current">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
                                    </svg>
                                </label>
                            </div>
                            <a href="{% url "core:home" %}"
                               class="flex items-center justify-between ml-2">
                                <img src="{% static 'images/favicon.png' %}"
                                     alt="Favicon"
                                     class="w-8 h-8 hidden lg:block"
                                     height="32"
                                     width="32" />
                                <div class="lg:ml-4 font-bold text-lg">Stockastic</div>
                            </a>
                        </div>
                        {% if user.is_authenticated %}
                            <div class="hidden flex-none lg:block">
                                <ul class="menu menu-horizontal">
                                    <li>
                                        <a href="{% url "core:explore" %}">Explore</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'stock:indices' %}">Indices</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'stock:equityTopGainers' %}">Gainers</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'stock:equityTopLosers' %}">Losers</a>
                                    </li>
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                    {% if user.is_authenticated %}
                        <div class="dropdown dropdown-end">
                            <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
                                <div class="w-10 rounded-full">
                                    {% if user.avatar %}
                                        <img alt="Profile" height="40" width="40" src="{{ user.avatar.url }}" />
                                    {% else %}
                                        <img alt="Profile"
                                             height="40"
                                             width="40"
                                             src="https://api.dicebear.com/9.x/fun-emoji/svg?seed={{ user.username }}" />
                                    {% endif %}
                                </div>
                            </div>
                            <ul tabindex="0"
                                class="menu menu-sm dropdown-content bg-gray-700 rounded-box z-[1] mt-3 w-52 p-2 shadow gap-1">
                                <li>
                                    <a href="{% url "dashboard:home" %}" class="py-3">Dashboard</a>
                                </li>
                                <hr />
                                <li>
                                    <a href="{% url "account:profile" %}" class="py-3">Profile</a>
                                </li>
                                <li>
                                    <a href="{% url "account:logout" %}" class="py-3">Logout</a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <div>
                            <div class="hidden flex-none lg:block">
                                <!-- Navbar menu content here -->
                                <ul class="menu menu-horizontal">
                                    <li>
                                        <a href="{% url "account:register" %}" class="font-semibold py-3">Register</a>
                                    </li>
                                    <li>
                                        <a href="{% url "account:login" %}" class="font-semibold py-3">Login</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    {% endif %}
                </div>
                {% block content %}
                {% endblock content %}
            </div>
            <div class="drawer-side">
                <label for="my-drawer-3" aria-label="close sidebar" class="drawer-overlay"></label>
                <!-- Sidebar content here -->
                <ul class="menu bg-base-200 h-full w-80 p-4 gap-2 z-50">
                    <li>
                        <a href="{% url "core:home" %}" class="flex items-center gap-4">
                            <img src="{% static 'images/favicon.png' %}"
                                 alt="Favicon"
                                 class="w-8 h-8"
                                 height="32"
                                 width="32" />
                            <div class="font-bold text-lg">Stockastic</div>
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "core:explore" %}" class="font-semibold py-3">Explore</a>
                        </li>
                        <li>
                            <a href="{% url 'stock:indices' %}" class="font-semibold py-3">Indices</a>
                        </li>
                        <li>
                            <a href="{% url 'stock:equityTopGainers' %}" class="font-semibold py-3">Gainers</a>
                        </li>
                        <li>
                            <a href="{% url 'stock:equityTopLosers' %}" class="font-semibold py-3">Losers</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "account:register" %}" class="font-semibold py-3">Register</a>
                        </li>
                        <li>
                            <a href="{% url "account:login" %}" class="font-semibold py-3">Login</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
        {% block style %}
        {% endblock style %}
        {% block script %}
        {% endblock script %}
    </body>
</html>