apps/dashboard/urls.py
# Imports
from django.urls import path

from apps.dashboard import views as dashboard_views

# Set the app name
app_name = "dashboard"

# URL patterns
urlpatterns = [
    path("dashboard/", dashboard_views.home_view, name="home"),
    path(
        "api/playground/getPeriodIntervals/",
        dashboard_views.get_period_intervals_view,
        name="getPeriodIntervals",
    ),
    path(
        "<str:symbol>/playground/", dashboard_views.playground_view, name="playground"
    ),
]

apps/stock/urls.py
# Imports
from django.urls import path

from apps.stock import views as stock_views

# Set the app name
app_name = "stock"

# URL patterns
urlpatterns = [
    path("indices/", stock_views.indices_view, name="indices"),
    path("indices/<str:symbol>/", stock_views.index_quote_view, name="indexQuote"),
    path(
        "indices/<str:symbol>/bookmark/",
        stock_views.index_quote_bookmark_view,
        name="indexQuoteBookmark",
    ),
    path(
        "indices/<str:symbol>/unbookmark/",
        stock_views.index_quote_unbookmark_view,
        name="indexQuoteUnbookmark",
    ),
    path(
        "api/indices/getCategories/",
        stock_views.get_categories_view,
        name="indicesGetCategories",
    ),
    path(
        "equity/topGainers/",
        stock_views.equity_top_gainers_view,
        name="equityTopGainers",
    ),
    path(
        "equity/topLosers/", stock_views.equity_top_losers_view, name="equityTopLosers"
    ),
    path("equity/<str:symbol>/", stock_views.equity_quote_view, name="equityQuote"),
    path(
        "equity/<str:symbol>/bookmark/",
        stock_views.equity_bookmark_view,
        name="equityQuoteBookmark",
    ),
    path(
        "equity/<str:symbol>/unbookmark/",
        stock_views.equity_unbookmark_view,
        name="equityQuoteUnbookmark",
    ),
]

config/urls.py
# Imports
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# Django admin urls
urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
]

# Health check urls
urlpatterns += [path("health/", include("health_check.urls"))]

# App urls
urlpatterns += [
    path("", include("apps.core.urls")),
    path("account/", include("apps.account.urls")),
    path("stock/", include("apps.stock.urls")),
    path("", include("apps.dashboard.urls")),
]

# If the app is in debug mode
if settings.DEBUG:
    # Add Silk profiler urls
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

# Admin configuration
admin.site.site_header = "Stockastic Admin"
admin.site.site_title = "Stockastic Admin"
admin.site.index_title = "Welcome to Stockastic Admin"

apps/dashboard/models.py
# Imports
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

# Get the user model
User = get_user_model()


# StockIndexWatchlist model
class StockIndexWatchlist(models.Model):
    """Model definition for StockIndexWatchlist.

    Inherits:
        models.Model

    Attributes:
        pkid: Primary key for the model
        id: UUIDField for the unique identifier
        user: ForeignKey to User model
        symbol: CharField for the symbol name
        type: CharField for the type of the symbol

    Meta:
        verbose_name: Singular name for the model
        verbose_name_plural: Plural name for the model

    Methods:
        __str__: Returns the string representation of the model
    """

    # Attributes
    pkid = models.BigAutoField(primary_key=True, editable=False)
    id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="stock_index_watchlists"
    )
    symbol = models.CharField(_("Symbol"), max_length=255)
    type = models.CharField(_("Type"), max_length=255, default="INDEX")

    # Meta
    class Meta:
        # Attributes
        verbose_name = _("StockIndex Watchlist")
        verbose_name_plural = _("StockIndex Watchlists")

    # String representation
    def __str__(self) -> str:
        # Return the string representation
        return f"{self.user} - {self.symbol} - {self.type}"

apps/dashboard/forms.py
# Imports
from django import forms

from apps.socket.constants import INDICATORS, INTERVALS, PERIODS


# Chart filter form
class ChartFilterForm(forms.Form):
    """Chart filter form

    Inherits:
        forms.Form

    Attributes:
        period (forms.ChoiceField): The period
        interval (forms.ChoiceField): The interval
    """

    # Attributes
    period = forms.ChoiceField(
        label="Period",
        choices=PERIODS,
        initial="1d",
        required=True,
        widget=forms.Select(),
    )
    interval = forms.ChoiceField(
        label="Interval",
        choices=INTERVALS["1d"],
        required=True,
        widget=forms.Select(),
    )
    indicator = forms.ChoiceField(
        label="Indicator",
        choices=INDICATORS,
        initial="none",
        required=True,
        widget=forms.Select(),
    )

apps/dashboard/views.py
# Imports
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from apps.dashboard.forms import ChartFilterForm
from apps.dashboard.models import StockIndexWatchlist
from apps.socket.constants import INTERVALS, PERIODS
from apps.socket.helpers import generate_candlestick_chart, get_quote
from apps.socket.utils import is_market_open


# Dashboard Home View
@login_required
def home_view(request):
    """Dashboard Home View

    Args:
        request (HttpRequest): The request object

    Returns:
        HttpResponse: The response object
    """

    # Fetch the bookmarked indices and stocks
    bookmarked_items = StockIndexWatchlist.objects.filter(user=request.user).order_by(
        "-type", "symbol"
    )

    # Dict to store the quotes
    quotes = {}

    # Traverse over the bookmarked items
    for item in bookmarked_items:
        # Get the quote for the item
        quote = get_quote(item.symbol)

        # Append the quote to the quotes dict
        quotes[quote[0]] = quote[1]

    # Create a context dictionary
    context = {
        "user": request.user,
        "is_market_open": is_market_open(),
        "quotes": quotes,
    }

    # Render the dashboard.html template
    return render(request, "dashboard/dashboard.html", context)


# Get Period Intervals View
def get_period_intervals_view(request):
    """Get Period Intervals View

    Args:
        request (HttpRequest): The request object

    Returns:
        JsonResponse: The response object
    """

    # Get the period from query parameters
    period = request.GET.get("period", "1d")

    # Return the intervals as a JSON response
    return JsonResponse({"intervals": INTERVALS[period]})


# Playground View
@login_required
def playground_view(request, symbol: str):
    """Playground View

    Args:
        request (HttpRequest): The request object

    Returns:
        HttpResponse: The response object
    """

    # Initialize the form
    form = ChartFilterForm(request.GET)

    # Get the period and interval
    period = form.data.get("period", "1d")
    interval = form.data.get("interval", "5m")
    indicator = form.data.get("indicator", "none")

    # Check if period and interval are valid
    if period not in dict(PERIODS) or interval not in dict(INTERVALS[period]):
        # Add a flash message
        messages.error(request, "Invalid period or interval")

        # Redirect to the dashboard
        return redirect(reverse("core:explore"))

    # Get the intervals for the period
    intervals = INTERVALS[period]

    # Set the initial interval
    form.fields["interval"].initial = interval

    # Set the choices for the interval field
    form.fields["interval"].choices = intervals

    # Set the initial indicator
    form.fields["indicator"].initial = indicator

    # Get the quote for the symbol
    quote = get_quote(symbol)

    # If the quote is None
    if quote is None:
        # Add a flash message
        messages.error(request, f"Invalid symbol: {symbol}")

        # Redirect to the dashboard
        return redirect(reverse("core:explore"))

    # Generate the candlestick chart
    chart = generate_candlestick_chart(symbol, period, interval, indicator, 800)

    # Create a context dictionary
    context = {
        "user": request.user,
        "is_market_open": is_market_open(),
        "form": form,
        "quote": quote[1],
        "chart": chart.to_html(),
        "period": period,
        "interval": interval,
        "indicator": indicator,
    }

    # Render the playground.html template
    return render(request, "dashboard/playground.html", context)

apps/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}
{% block content %}
    <div class="mx-4 xl:mx-auto mt-8 xl:max-w-screen-xl xl:w-full xl:space-x-0 xl:justify-between">
        {% if messages %}
            {% for msg in messages %}
                <div role="alert" class="alert alert-{{ msg.tags }} my-4 relative">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         class="h-6 w-6 shrink-0 stroke-current inline-block">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z">
                        </path>
                    </svg>
                    <span class="text-sm inline-block">{{ msg }}</span>
                    <button type="button"
                            class="absolute right-0 p-4"
                            onclick="this.parentElement.style.display='none';">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             fill="none"
                             viewBox="0 0 24 24"
                             stroke-width="1.5"
                             stroke="currentColor"
                             class="h-6 w-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
        <h1 class="text-3xl font-bold text-white w-full text-center mb-6">Dashboard</h1>
        {% if quotes %}
            <div class="flex flex-col gap-2 mt-8 mb-6">
                <div class="overflow-x-auto no-scrollbar">
                    <table class="z-0 table table-zebra table-xs lg:table-md table-pin-rows table-pin-cols min-w-full [&_td]:py-2 [&_th]:py-2 lg:[&_td]:py-4 lg:[&_th]:py-4">
                        <thead>
                            <tr>
                                <th></th>
                                <td>Name</td>
                                <td>Type</td>
                                <td>Exchange</td>
                                <td>Curr Price</td>
                                <td>Day Change</td>
                                <td>% Change</td>
                                <td>Prev Close</td>
                                <td>Open</td>
                                <td>High</td>
                                <td>Low</td>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for symbol, quote in quotes.items %}
                                <tr id="{{ quote.symbol }}">
                                    <th>{{ forloop.counter }}</th>
                                    <td>
                                        {% if quote.quoteType == "INDEX" %}
                                            <a href="{% url 'stock:indexQuote' symbol %}">
                                                {% if quote.longName %}
                                                    {{ quote.longName|upper }}
                                                {% else %}
                                                    {{ quote.shortName|upper }}
                                                {% endif %}
                                            </a>
                                        {% else %}
                                            <a href="{% url 'stock:equityQuote' symbol %}">
                                                {% if quote.longName %}
                                                    {{ quote.longName|upper }}
                                                {% else %}
                                                    {{ quote.shortName|upper }}
                                                {% endif %}
                                            </a>
                                        {% endif %}
                                    </td>
                                    <td>{{ quote.quoteType }}</td>
                                    <td>{{ quote.exchange }}</td>
                                    <td class="{{ quote.colorClass }}">₹{{ quote.lastPrice|floatformat:2|intcomma }}</td>
                                    <td class="{{ quote.colorClass }}">
                                        {% if quote.dayChange >= 0 %}
                                            +{{ quote.dayChange|floatformat:2|intcomma }}
                                        {% else %}
                                            {{ quote.dayChange|floatformat:2|intcomma }}
                                        {% endif %}
                                    </td>
                                    <td class="{{ quote.colorClass }}">
                                        {% if quote.dayChangePercentage >= 0 %}
                                            +{{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                                        {% else %}
                                            {{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                                        {% endif %}
                                    </td>
                                    <td>₹{{ quote.previousClose|floatformat:2|intcomma }}</td>
                                    <td>₹{{ quote.open|floatformat:2|intcomma }}</td>
                                    <td>₹{{ quote.dayHigh|floatformat:2|intcomma }}</td>
                                    <td>₹{{ quote.dayLow|floatformat:2|intcomma }}</td>
                                    <th>{{ forloop.counter }}</th>
                                </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <td>Name</td>
                                <td>Type</td>
                                <td>Exchange</td>
                                <td>Curr Price</td>
                                <td>Day Change</td>
                                <td>% Change</td>
                                <td>Prev Close</td>
                                <td>Open</td>
                                <td>High</td>
                                <td>Low</td>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="flex flex-col items-center justify-center mt-8">
                <p class="text-lg text-white">No Indices/Stocks Bookmarked!</p>
            </div>
        {% endif %}
    </div>
{% endblock content %}
{% block script %}
    <script>
        let socket;

        function updateAllIndices(data) {
            const quotes = data || {};

            Object.entries(quotes).forEach(([symbol, quote]) => {
                const row = document.getElementById(symbol);

                if (row) {
                    const cells = row.querySelectorAll('td');

                    const priceCell = cells[4];
                    if (priceCell) {
                        priceCell.textContent = `₹${parseFloat(quote.lastPrice).toLocaleString('en-IN', {
                            minimumFractionDigits: 2,
                            maximumFractionDigits: 2
                        })}`;
                    }

                    const chagneCel = cells[5];
                    if (changeCell) {
                        const change = parseFloat(quote.dayChange).toLocaleString('en-IN', {
                            minimumFractionDigits: 2,
                            maximumFractionDigits: 2
                        });
                        changeCell.textContent = `${quote.dayChange >= 0 ? '+' : ''}${change}`;
                    }

                    const percentCell = cells[6];
                    if (percentCell) {
                        const dayChangePercentage = parseFloat(quote.dayChangePercentage);
                        percentCell.textContent = `${dayChangePercentage >= 0 ? '+' : ''}${dayChangePercentage.toFixed(2)}%`;
                    }

                    const colorClass = quote.dayChange >= 0 ? 'text-green-500' : 'text-red-500';
                    [priceCell, changeCell, percentCell].forEach(cell => {
                        if (cell) {
                            cell.classList.remove('text-green-500', 'text-red-500');
                            cell.classList.add(colorClass);
                        }
                    });
                }
            });
        }

        document.addEventListener('DOMContentLoaded', () => {
            {% if is_market_open %}
                const socketUrl = `ws://${window.location.host}ws/{{request.user.id}}/bookmarkQuotes/`;
                socket = new WebSocket(socketUrl);

                socket.onopen = function () {
                    console.log("WebSocket connection established");
                };

                socket.onmessage = function (event) {
                    try {
                        const data = JSON.parse(event.data);
                        updateAllIndices(data);
                    } catch (error) {
                        console.error("Error parsing WebSocket message:", error);
                    }
                };

                socket.onclose = function () {
                    console.log("WebSocket connection closed");
                };

                socket.onerror = function (error) {
                    console.error("WebSocket error:", error);
                };
            {% else %}
                console.log("Market is closed. Not connecting to WebSocket.");
            {% endif %}
        });
    </script>
{% endblock script %}

apps/templates/dashboard/playground.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}
{% block content %}
    <div class="mx-4 xl:mx-auto mt-8 xl:max-w-[118rem] xl:w-full xl:space-x-0 xl:justify-between">
        {% if messages %}
            {% for msg in messages %}
                <div role="alert" class="alert alert-{{ msg.tags }} my-4 relative">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         class="h-6 w-6 shrink-0 stroke-current inline-block">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z">
                        </path>
                    </svg>
                    <span class="text-sm inline-block">{{ msg }}</span>
                    <button type="button"
                            class="absolute right-0 p-4"
                            onclick="this.parentElement.style.display='none';">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             fill="none"
                             viewBox="0 0 24 24"
                             stroke-width="1.5"
                             stroke="currentColor"
                             class="h-6 w-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
        <div class="flex items-center justify-center w-full text-center mb-3.5">
            <h1 class="text-2xl lg:text-3xl font-black text-white mr-3">
                {% if quote.longName %}
                    {{ quote.longName|upper }} ({{ quote.exchange|upper }})
                {% else %}
                    {{ quote.shortName|upper }} ({{ quote.exchange|upper }})
                {% endif %}
            </h1>
        </div>
        <div id="chart-container">{{ chart|safe }}</div>
        <div class="flex flex-col gap-2 mb-6 mt-8">
            <form method="get"
                  action="{% url 'dashboard:playground' quote.symbol %}"
                  class="mx-0 w-full xl:mx-auto xl:max-w-7xl">
                <div class="flex flex-col gap-0 md:flex-row md:gap-2 align-center justify-between">
                    <div class="mb-2 form-control w-full">
                        {{ form.period|add_label_class:"label text-white text-xs md:text-sm" }}
                        {% render_field form.period class="select bg-gray-50 text-gray-900 text-xs md:text-sm" onchange="updateIntervals()" %}
                    </div>
                    <div class="mb-2 form-control w-full">
                        {{ form.interval|add_label_class:"label text-white text-xs md:text-sm" }}
                        {% render_field form.interval class="select bg-gray-50 text-gray-900 text-xs md:text-sm" %}
                    </div>
                    <div class="mb-2 form-control w-full">
                        {{ form.indicator|add_label_class:"label text-white text-xs md:text-sm" }}
                        {% render_field form.indicator class="select bg-gray-50 text-gray-900 text-xs md:text-sm" %}
                    </div>
                </div>
                <button type="submit" class="w-full btn btn-success text-xs">Update</button>
            </form>
        </div>
    </div>
{% endblock content %}
{% block script %}
    <script>
        function updateIntervals() {
            const period = document.getElementById('{{ form.period.id_for_label }}').value;
            const intervalSelect = document.getElementById('{{ form.interval.id_for_label }}');

            fetch(`{% url 'dashboard:getPeriodIntervals' %}?period=${period}`)
                .then(response => response.json())
                .then(data => {
                    intervalSelect.innerHTML = '';
                    data.intervals.forEach(([value, label]) => {
                        const option = new Option(label, value);
                        intervalSelect.add(option);
                    });
                })
                .catch(error => console.error('Error:', error));
        }

        document.getElementById('{{ form.period.id_for_label }}').addEventListener('change', updateIntervals);

        document.addEventListener('DOMContentLoaded', function () {
            if (!('WebSocket' in window)) {
                console.error("WebSocket not supported in this browser.");
                return;
            }

            const isMarketOpen = {{ is_market_open|lower }};
            if (!isMarketOpen) {
                console.log("Market is closed. Not connecting to WebSocket.");
                return;
            }

            const symbol = "{{ symbol }}";
            const period = "{{ period }}";
            const interval = "{{ interval }}";
            const indicator = "{{ indicator }}";
            const ws = new WebSocket(`ws://${window.location.host}/ws/quote/${symbol}/chart/?period=${period}&interval=${interval}&indicator=${indicator}`);

            ws.onmessage = function (event) {
                try {
                    const chartContainer = document.getElementById('chart-container');
                    if (!chartContainer) {
                        console.error('Chart container element not found');
                        return;
                    }

                    const oldScripts = document.querySelectorAll('script[data-chart-script]');
                    oldScripts.forEach(script => script.remove());

                    chartContainer.innerHTML = event.data;

                    const scripts = chartContainer.querySelectorAll('script');
                    scripts.forEach(script => {
                        const newScript = document.createElement('script');
                        newScript.type = script.type || 'text/javascript';
                        newScript.setAttribute('data-chart-script', 'true');

                        if (script.src) {
                            newScript.src = script.src;
                            newScript.async = false;
                            document.head.appendChild(newScript);
                        } else {
                            newScript.textContent = script.textContent;
                            document.body.appendChild(newScript);
                        }

                        script.remove();
                    });
                } catch (error) {
                    console.error('Error rendering chart:', error);
                }
            };


            ws.onerror = function (error) {
                console.error('WebSocket error:', error);
            };

            ws.onclose = function () {
                console.log('WebSocket connection closed');
            };
        });
    </script>
{% endblock script %}