apps/core/urls.py
# Imports
from django.urls import path

from apps.core import views as core_views

# Set the app name
app_name = "core"

# URL patterns
urlpatterns = [
    path("", core_views.home_view, name="home"),
    path("explore/", core_views.explore_view, name="explore"),
]

apps/stock/urls.py
# Imports
from django.urls import path

from apps.stock import views as stock_views

# Set the app name
app_name = "stock"

# URL patterns
urlpatterns = [
    path("indices/", stock_views.indices_view, name="indices"),
    path("indices/<str:symbol>/", stock_views.index_quote_view, name="indexQuote"),
    path(
        "indices/<str:symbol>/bookmark/",
        stock_views.index_quote_bookmark_view,
        name="indexQuoteBookmark",
    ),
    path(
        "indices/<str:symbol>/unbookmark/",
        stock_views.index_quote_unbookmark_view,
        name="indexQuoteUnbookmark",
    ),
    path(
        "api/indices/getCategories/",
        stock_views.get_categories_view,
        name="indicesGetCategories",
    ),
    path(
        "equity/topGainers/",
        stock_views.equity_top_gainers_view,
        name="equityTopGainers",
    ),
    path(
        "equity/topLosers/", stock_views.equity_top_losers_view, name="equityTopLosers"
    ),
    path("equity/<str:symbol>/", stock_views.equity_quote_view, name="equityQuote"),
    path(
        "equity/<str:symbol>/bookmark/",
        stock_views.equity_bookmark_view,
        name="equityQuoteBookmark",
    ),
    path(
        "equity/<str:symbol>/unbookmark/",
        stock_views.equity_unbookmark_view,
        name="equityQuoteUnbookmark",
    ),
]

config/urls.py
# Imports
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# Django admin urls
urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
]

# Health check urls
urlpatterns += [path("health/", include("health_check.urls"))]

# App urls
urlpatterns += [
    path("", include("apps.core.urls")),
    path("account/", include("apps.account.urls")),
    path("stock/", include("apps.stock.urls")),
    path("", include("apps.dashboard.urls")),
]

# If the app is in debug mode
if settings.DEBUG:
    # Add Silk profiler urls
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

# Admin configuration
admin.site.site_header = "Stockastic Admin"
admin.site.site_title = "Stockastic Admin"
admin.site.index_title = "Welcome to Stockastic Admin"

apps/core/views.py
# Imports
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse

from apps.socket.helpers import (
    get_top_equity_gainers_quotes,
    get_top_equity_losers_quotes,
    get_top_index_quotes,
)
from apps.socket.utils import is_market_open


# Home view
def home_view(request):
    """Home view

    Args:
        request (HttpRequest): The request object

    Returns:
        HttpResponse: The response object
    """

    # If user is authenticated
    if request.user.is_authenticated:
        # Redirect to explore view
        return redirect(reverse("core:explore"))

    # Create a context dictionary
    context = {"user": request.user}

    # Render the home.html template
    return render(request, "core/home.html", context)


# Explore view
@login_required
def explore_view(request):
    """Explore view

    Args:
        request (HttpRequest): The request object

    Returns:
        HttpResponse: The response object
    """

    # Create a context dictionary
    context = {
        "user": request.user,
        "indices": get_top_index_quotes(),
        "gainers": get_top_equity_gainers_quotes(),
        "losers": get_top_equity_losers_quotes(),
        "is_market_open": is_market_open(),
    }

    # Render the explore.html template
    return render(request, "core/explore.html", context)

apps/templates/core/partials/top_gainers.html
{% load humanize %}
<h1 class="text-xl font-bold text-white w-full text-center mb-4">Top Gainers</h1>
<div class="flex items-center justify-center gap-4 m-4 xl:max-w-screen">
    <div class="grid grid-cols-2 lg:grid-cols-3 gap-2 text-xxs md:text-xs text-gray-300 xl:max-w-screen-xl w-full"
         id="explore-top-gainers">
        {% for symbol, quote in gainers.items %}
            <a href="{% url 'stock:equityQuote' symbol %}"
               class="card bg-neutral text-neutral-content rounded-md h-20 md:h-[4.5rem] cursor-pointer"
               id="top-gainer-card-{{ forloop.counter }}">
                <div class="p-4 h-full flex flex-col justify-center items-start space-y-1">
                    <div class="flex items-center justify-between w-full space-x-2">
                        <p class="font-bold text-white"
                           id="top-gainer-name-{{ forloop.counter }}">
                            {% if quote.longName %}
                                {{ quote.longName|upper }}
                            {% else %}
                                {{ quote.shortName|upper }}
                            {% endif %}
                        </p>
                        <span class="text-blue-100 text-semibold">NSE</span>
                    </div>
                    <div class="flex items-center justify-between w-full">
                        <p class="quote-price {{ quote.colorClass }}"
                           id="top-gainer-price-{{ forloop.counter }}">{{ quote.lastPrice|floatformat:2|intcomma }}</p>
                        <span class="quote-change {{ quote.colorClass }}"
                              id="top-gainer-change-{{ forloop.counter }}">
                            {% if quote.dayChange >= 0 %}
                                +{{ quote.dayChange|floatformat:2|intcomma }}
                            {% else %}
                                {{ quote.dayChange|floatformat:2|intcomma }}
                            {% endif %}
                        </span>
                        <span class="quote-percent {{ quote.colorClass }}"
                              id="top-gainer-percent-{{ forloop.counter }}">
                            {% if quote.dayChangePercentage >= 0 %}
                                +{{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                            {% else %}
                                {{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                            {% endif %}
                        </span>
                    </div>
                </div>
            </a>
        {% endfor %}
        <div class="card bg-neutral text-neutral-content rounded-md h-20 md:h-[4.5rem]">
            <a href="{% url "stock:equityTopGainers" %}"
               class="p-4 h-full flex flex-col justify-center items-start cursor-pointer space-y-1">
                <p class="font-bold text-white flex items-center justify-center">
                    See More
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="2"
                         stroke="currentColor"
                         class="h-4 w-4 ml-1">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>
                </p>
                <p class="text-gray-300 text-semibold">Gainers</p>
            </a>
        </div>
    </div>
</div>
{% block script %}
    <script>
    document.addEventListener('DOMContentLoaded', () => {
        {% if is_market_open %}
            if ("WebSocket" in window) {
                const socketUrl = `ws://${window.location.host}/ws/topEquityGainersQuotes/`;
                const socket = new WebSocket(socketUrl);

                socket.onerror = function(error) {
                    console.error('WebSocket Error:', error);
                };

                socket.onopen = function () {
                    console.log("WebSocket connection established");
                };

                socket.onmessage = function (event) {
                    const quotes = JSON.parse(event.data);

                    Object.entries(quotes).forEach(([symbol, quote], index) => {
                        const uniqueId = index + 1;

                        const card = document.getElementById(`top-gainer-card-${uniqueId}`);
                        const nameElement = document.getElementById(`top-gainer-name-${uniqueId}`);
                        const priceElement = document.getElementById(`top-gainer-price-${uniqueId}`);
                        const changeElement = document.getElementById(`top-gainer-change-${uniqueId}`);
                        const percentElement = document.getElementById(`top-gainer-percent-${uniqueId}`);

                        if (nameElement) {
                            nameElement.textContent = quote.longName ? quote.longName.toUpperCase() : quote.shortName.toUpperCase();
                        }

                        if (priceElement) {
                            priceElement.textContent = parseFloat(quote.lastPrice).toLocaleString('en-IN', {
                                minimumFractionDigits: 2,
                                maximumFractionDigits: 2
                            });

                            const colorClass = quote.dayChange >= 0 ? 'text-green-500' : 'text-red-500';

                            ['text-green-500', 'text-red-500'].forEach(cls => {
                                priceElement.classList.remove(cls);
                                changeElement?.classList.remove(cls);
                                percentElement?.classList.remove(cls);
                            });

                            priceElement.classList.add(colorClass);
                            changeElement?.classList.add(colorClass);
                            percentElement?.classList.add(colorClass);
                        }

                        if (changeElement) {
                            const change = parseFloat(quote.dayChange);
                            changeElement.textContent = `${change >= 0 ? '+' : ''}${change.toFixed(2)}`;
                        }

                        if (percentElement) {
                            const dayChangePercentage = parseFloat(quote.dayChangePercentage);
                            percentElement.textContent = `${dayChangePercentage >= 0 ? '+' : ''}${dayChangePercentage.toFixed(2)}%`;
                        }
                    });
                };

                socket.onclose = function (event) {
                    console.error("WebSocket connection closed:", event);
                };

                socket.onerror = function (error) {
                    console.error("WebSocket error:", error);
                };
            } else {
                console.error("WebSocket not supported in this browser.");
            }
        {% else %}
            console.log("Market is closed. Not connecting to WebSocket.");
        {% endif %}
    });
    </script>
{% endblock script %}

apps/templates/core/partials/top_indices.html
{% load humanize %}
<h1 class="text-xl font-bold text-white w-full text-center mb-4">Stock Indices</h1>
<div class="flex items-center justify-center gap-4 m-4 xl:max-w-screen">
    <div class="flex overflow-scroll no-scrollbar space-x-2 text-xxs md:text-xs text-gray-300 xl:max-w-screen-xl w-full xl:space-x-0 xl:justify-between"
         id="explore-top-indices">
        {% for symbol, quote in indices.items %}
            <a href="{% url 'stock:indexQuote' symbol %}"
               class="card bg-neutral text-neutral-content rounded-md h-16 md:h-[4.5rem] cursor-pointer"
               id="{{ quote.longName|slugify }}-card">
                <div class="w-[11.5rem] md:w-52 p-4 h-full flex flex-col justify-center items-start space-y-1">
                    <p class="font-bold text-white">
                        {% if quote.longName %}
                            {{ quote.longName|upper }}
                        {% else %}
                            {{ quote.shortName|upper }}
                        {% endif %}
                    </p>
                    <div class="flex items-center justify-between w-full">
                        <p class="quote-price {{ quote.colorClass }}"
                           id="{{ quote.longName|slugify }}-price">{{ quote.lastPrice|floatformat:2|intcomma }}</p>
                        <span class="quote-change {{ quote.colorClass }}"
                              id="{{ quote.longName|slugify }}-change">
                            {% if quote.dayChange >= 0 %}
                                +{{ quote.dayChange|floatformat:2|intcomma }}
                            {% else %}
                                {{ quote.dayChange|floatformat:2|intcomma }}
                            {% endif %}
                        </span>
                        <span class="quote-percent {{ quote.colorClass }}"
                              id="{{ quote.longName|slugify }}-percent">
                            {% if quote.dayChangePercentage >= 0 %}
                                +{{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                            {% else %}
                                {{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                            {% endif %}
                        </span>
                    </div>
                </div>
            </a>
        {% endfor %}
        <div class="card bg-neutral text-neutral-content rounded-md h-16 md:h-[4.5rem]">
            <a href="{% url 'stock:indices' %}"
               class="w-[11.5rem] md:w-52 p-4 h-full flex flex-col justify-center items-start cursor-pointer space-y-1">
                <p class="font-bold text-white flex items-center justify-center">
                    All Indices
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="2"
                         stroke="currentColor"
                         class="h-4 w-4 ml-1">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>
                </p>
                <p class="text-gray-300 text-semibold">Indian and Global</p>
            </a>
        </div>
    </div>
</div>
{% block script %}
    <script>
    document.addEventListener('DOMContentLoaded', () => {
        {% if is_market_open %}
            if ("WebSocket" in window) {
                const socketUrl = `ws://${window.location.host}/ws/topIndexQuotes/`;
                const socket = new WebSocket(socketUrl);

                socket.onerror = function(error) {
                    console.error('WebSocket Error:', error);
                };

                socket.onopen = function () {
                    console.log("WebSocket connection established");
                };

                socket.onmessage = function (event) {
                    const quotes = JSON.parse(event.data);

                    Object.entries(quotes).forEach(([symbol, quote]) => {
                        const slugifiedSymbol = slugify(quote.longName);

                        const card = document.getElementById(`${slugifiedSymbol}-card`);
                        const priceElement = document.getElementById(`${slugifiedSymbol}-price`);
                        const changeElement = document.getElementById(`${slugifiedSymbol}-change`);
                        const percentElement = document.getElementById(`${slugifiedSymbol}-percent`);

                        if (priceElement) {
                            priceElement.textContent = parseFloat(quote.lastPrice).toLocaleString('en-IN', {
                                minimumFractionDigits: 2,
                                maximumFractionDigits: 2
                            });

                            const colorClass = quote.dayChange >= 0 ? 'text-green-500' : 'text-red-500';

                            ['text-green-500', 'text-red-500'].forEach(cls => {
                                priceElement.classList.remove(cls);
                                changeElement?.classList.remove(cls);
                                percentElement?.classList.remove(cls);
                            });

                            priceElement.classList.add(colorClass);
                            changeElement?.classList.add(colorClass);
                            percentElement?.classList.add(colorClass);
                        }

                        if (changeElement) {
                            const change = parseFloat(quote.dayChange);
                            changeElement.textContent = `${change >= 0 ? '+' : ''}${change.toFixed(2)}`;
                        }

                        if (percentElement) {
                            const dayChangePercentage = parseFloat(quote.dayChangePercentage);
                            percentElement.textContent = `${dayChangePercentage >= 0 ? '+' : ''}${dayChangePercentage.toFixed(2)}%`;
                        }
                    });
                };

                socket.onclose = function (event) {
                    console.error("WebSocket connection closed:", event);
                };

                socket.onerror = function (error) {
                    console.error("WebSocket error:", error);
                };
            } else {
                console.error("WebSocket not supported in this browser.");
            }
        {% else %}
            console.log("Market is closed. Not connecting to WebSocket.");
        {% endif %}
    });
    </script>
{% endblock script %}

apps/templates/core/partials/top_losers.html
{% load humanize %}
<h1 class="text-xl font-bold text-white w-full text-center mb-4">Top Losers</h1>
<div class="flex items-center justify-center gap-4 m-4 xl:max-w-screen">
    <div class="grid grid-cols-2 lg:grid-cols-3 gap-2 text-xxs md:text-xs text-gray-300 xl:max-w-screen-xl w-full"
         id="explore-top-losers">
        {% for symbol, quote in losers.items %}
            <a href="{% url 'stock:equityQuote' symbol %}"
               class="card bg-neutral text-neutral-content rounded-md h-20 md:h-[4.5rem] cursor-pointer"
               id="top-loser-card-{{ forloop.counter }}">
                <div class="p-4 h-full flex flex-col justify-center items-start space-y-1">
                    <div class="flex items-center justify-between w-full space-x-2">
                        <p class="font-bold text-white"
                           id="top-loser-name-{{ forloop.counter }}">
                            {% if quote.longName %}
                                {{ quote.longName|upper }}
                            {% else %}
                                {{ quote.shortName|upper }}
                            {% endif %}
                        </p>
                        <span class="text-blue-100 text-semibold">NSE</span>
                    </div>
                    <div class="flex items-center justify-between w-full">
                        <p class="quote-price {{ quote.colorClass }}"
                           id="top-loser-price-{{ forloop.counter }}">{{ quote.lastPrice|floatformat:2|intcomma }}</p>
                        <span class="quote-change {{ quote.colorClass }}"
                              id="top-loser-change-{{ forloop.counter }}">
                            {% if quote.dayChange >= 0 %}
                                +{{ quote.dayChange|floatformat:2|intcomma }}
                            {% else %}
                                {{ quote.dayChange|floatformat:2|intcomma }}
                            {% endif %}
                        </span>
                        <span class="quote-percent {{ quote.colorClass }}"
                              id="top-loser-percent-{{ forloop.counter }}">
                            {% if quote.dayChangePercentage >= 0 %}
                                +{{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                            {% else %}
                                {{ quote.dayChangePercentage|floatformat:2|intcomma }}%
                            {% endif %}
                        </span>
                    </div>
                </div>
            </a>
        {% endfor %}
        <div class="card bg-neutral text-neutral-content rounded-md h-20 md:h-[4.5rem]">
            <a href="{% url "stock:equityTopLosers" %}"
               class="p-4 h-full flex flex-col justify-center items-start cursor-pointer space-y-1">
                <p class="font-bold text-white flex items-center justify-center">
                    See More
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="2"
                         stroke="currentColor"
                         class="h-4 w-4 ml-1">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>
                </p>
                <p class="text-gray-300 text-semibold">Losers</p>
            </a>
        </div>
    </div>
</div>
{% block script %}
    <script>
    document.addEventListener('DOMContentLoaded', () => {
        {% if is_market_open %}
            if ("WebSocket" in window) {
                const socketUrl = `ws://${window.location.host}/ws/topEquityLosersQuotes/`;
                const socket = new WebSocket(socketUrl);

                socket.onerror = function(error) {
                    console.error('WebSocket Error:', error);
                };

                socket.onopen = function () {
                    console.log("WebSocket connection established");
                };

                socket.onmessage = function (event) {
                    const quotes = JSON.parse(event.data);

                    Object.entries(quotes).forEach(([symbol, quote], index) => {
                        const uniqueId = index + 1;

                        const card = document.getElementById(`top-loser-card-${uniqueId}`);
                        const nameElement = document.getElementById(`top-loser-name-${uniqueId}`);
                        const priceElement = document.getElementById(`top-loser-price-${uniqueId}`);
                        const changeElement = document.getElementById(`top-loser-change-${uniqueId}`);
                        const percentElement = document.getElementById(`top-loser-percent-${uniqueId}`);

                        if (nameElement) {
                            nameElement.textContent = quote.longName ? quote.longName.toUpperCase() : quote.shortName.toUpperCase();
                        }

                        if (priceElement) {
                            priceElement.textContent = parseFloat(quote.lastPrice).toLocaleString('en-IN', {
                                minimumFractionDigits: 2,
                                maximumFractionDigits: 2
                            });

                            const colorClass = quote.dayChange >= 0 ? 'text-green-500' : 'text-red-500';

                            ['text-green-500', 'text-red-500'].forEach(cls => {
                                priceElement.classList.remove(cls);
                                changeElement?.classList.remove(cls);
                                percentElement?.classList.remove(cls);
                            });

                            priceElement.classList.add(colorClass);
                            changeElement?.classList.add(colorClass);
                            percentElement?.classList.add(colorClass);
                        }

                        if (changeElement) {
                            const change = parseFloat(quote.dayChange);
                            changeElement.textContent = `${change >= 0 ? '+' : ''}${change.toFixed(2)}`;
                        }

                        if (percentElement) {
                            const dayChangePercentage = parseFloat(quote.dayChangePercentage);
                            percentElement.textContent = `${dayChangePercentage >= 0 ? '+' : ''}${dayChangePercentage.toFixed(2)}%`;
                        }
                    });
                };

                socket.onclose = function (event) {
                    console.error("WebSocket connection closed:", event);
                };

                socket.onerror = function (error) {
                    console.error("WebSocket error:", error);
                };
            } else {
                console.error("WebSocket not supported in this browser.");
            }
        {% else %}
            console.log("Market is closed. Not connecting to WebSocket.");
        {% endif %}
    });
    </script>
{% endblock script %}